version: "3"
services:
  proxy:
    image: "nginx:latest"
    restart: unless-stopped
    volumes:
      - ./proxy/conf.d:/etc/nginx/conf.d
    ports:
      - "4500:80"
    networks:
      - frontend
      - backend

  frontend:
    build:
      context: frontend
      dockerfile: "Dockerfile.dev"
    stdin_open: true
    environment:
      - CHOKIDAR_USEPOLLING=true
      - WDS_SOCKET_PORT=4500
    restart: unless-stopped
    volumes:
      - "./frontend/src:/usr/src/app/src"
      - "./frontend/public:/usr/src/app/public"
    networks:
      - frontend

  backend:
    build:
      context: backend
      dockerfile: "Dockerfile.dev"
    restart: unless-stopped
    volumes:
      - "./backend/src:/usr/src/app/src"
    networks:
      - backend

networks:
  backend:
  frontend:
