# This workflow will do a clean installation of node dependencies, cache/restore them and format the source code
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Format

on:
  push:

jobs:
  frontend-format:
    name: Frontend Format
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 16
        uses: actions/setup-node@v3
        with:
          node-version: "16"
          cache: "npm"
          cache-dependency-path: frontend/package-lock.json
      - name: Frontend NPM Install
        working-directory: ./frontend
        run: npm ci
      - name: Frontend Format
        working-directory: ./frontend
        run: npm run format

  backend-format:
    name: Backend Format
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 16
        uses: actions/setup-node@v3
        with:
          node-version: "16"
          cache: "npm"
          cache-dependency-path: backend/package-lock.json
      - name: Backend NPM Install
        working-directory: ./backend
        run: npm ci
      - name: Backend Format
        working-directory: ./backend
        run: npm run format
