# This workflow will do a clean installation of node dependencies, cache/restore them and lint the source code
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Lint

on:
  push:

jobs:
  frontend-lint:
    name: Frontend Lint
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - name: Frontend NPM Install
      working-directory: ./frontend
      run: npm ci
    - name: Frontend Lint
      working-directory: ./frontend
      run: npm run lint
    
  backend-lint:
    name: Backend Lint
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - name: Backend NPM Install
      working-directory: ./backend
      run: npm ci
    - name: Backend Lint
      working-directory: ./backend
      run: npm run lint
